# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri May  5 22:28:06 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 475)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 40, 91, 198))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.stopButton = QtGui.QPushButton(self.formLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.stopButton)
        self.connectButton = QtGui.QPushButton(self.formLayoutWidget)
        self.connectButton.setObjectName("connectButton")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.connectButton)
        self.resetButton = QtGui.QPushButton(self.formLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.resetButton)
        self.enableMotorsButton = QtGui.QPushButton(self.formLayoutWidget)
        self.enableMotorsButton.setObjectName("enableMotorsButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.enableMotorsButton)
        self.disableMotorsButton = QtGui.QPushButton(self.formLayoutWidget)
        self.disableMotorsButton.setObjectName("disableMotorsButton")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.disableMotorsButton)
        self.startButton = QtGui.QPushButton(self.formLayoutWidget)
        self.startButton.setObjectName("startButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.startButton)
        self.initButton = QtGui.QPushButton(self.formLayoutWidget)
        self.initButton.setObjectName("initButton")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.initButton)
        self.imageGraphics = QtGui.QGraphicsView(self.centralWidget)
        self.imageGraphics.setGeometry(QtCore.QRect(280, 10, 400, 400))
        self.imageGraphics.setObjectName("imageGraphics")
        self.robotStateList = QtGui.QListView(self.centralWidget)
        self.robotStateList.setGeometry(QtCore.QRect(120, 210, 141, 197))
        self.robotStateList.setObjectName("robotStateList")
        self.yLine = QtGui.QLineEdit(self.centralWidget)
        self.yLine.setGeometry(QtCore.QRect(150, 150, 113, 22))
        self.yLine.setObjectName("yLine")
        self.zLine = QtGui.QLineEdit(self.centralWidget)
        self.zLine.setGeometry(QtCore.QRect(150, 180, 113, 22))
        self.zLine.setObjectName("zLine")
        self.xLine = QtGui.QLineEdit(self.centralWidget)
        self.xLine.setGeometry(QtCore.QRect(150, 120, 113, 22))
        self.xLine.setObjectName("xLine")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(130, 123, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(130, 154, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(130, 183, 16, 16))
        self.label_3.setObjectName("label_3")
        self.plainTextEdit = QtGui.QPlainTextEdit(self.centralWidget)
        self.plainTextEdit.setGeometry(QtCore.QRect(120, 10, 141, 101))
        self.plainTextEdit.setObjectName("plainTextEdit")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 697, 19))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.enableMotorsButton.setText(QtGui.QApplication.translate("MainWindow", "Motors Enb", None, QtGui.QApplication.UnicodeUTF8))
        self.disableMotorsButton.setText(QtGui.QApplication.translate("MainWindow", "Motors Dis", None, QtGui.QApplication.UnicodeUTF8))
        self.startButton.setText(QtGui.QApplication.translate("MainWindow", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.initButton.setText(QtGui.QApplication.translate("MainWindow", "Init", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))

