# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Fri Jun  9 16:29:14 2017
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(697, 475)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.formLayoutWidget = QtGui.QWidget(self.centralWidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 91, 405))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.stopButton = QtGui.QPushButton(self.formLayoutWidget)
        self.stopButton.setObjectName("stopButton")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.stopButton)
        self.connectButton = QtGui.QPushButton(self.formLayoutWidget)
        self.connectButton.setObjectName("connectButton")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.connectButton)
        self.resetButton = QtGui.QPushButton(self.formLayoutWidget)
        self.resetButton.setObjectName("resetButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.resetButton)
        self.enableMotorsButton = QtGui.QPushButton(self.formLayoutWidget)
        self.enableMotorsButton.setObjectName("enableMotorsButton")
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.enableMotorsButton)
        self.disableMotorsButton = QtGui.QPushButton(self.formLayoutWidget)
        self.disableMotorsButton.setObjectName("disableMotorsButton")
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.disableMotorsButton)
        self.startWhiteButton = QtGui.QPushButton(self.formLayoutWidget)
        self.startWhiteButton.setObjectName("startWhiteButton")
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.startWhiteButton)
        self.initWhiteButton = QtGui.QPushButton(self.formLayoutWidget)
        self.initWhiteButton.setObjectName("initWhiteButton")
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.initWhiteButton)
        self.initBlackButton = QtGui.QPushButton(self.formLayoutWidget)
        self.initBlackButton.setObjectName("initBlackButton")
        self.formLayout.setWidget(9, QtGui.QFormLayout.LabelRole, self.initBlackButton)
        self.startBlackButton = QtGui.QPushButton(self.formLayoutWidget)
        self.startBlackButton.setObjectName("startBlackButton")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.startBlackButton)
        self.gotoXYZButton = QtGui.QPushButton(self.formLayoutWidget)
        self.gotoXYZButton.setObjectName("gotoXYZButton")
        self.formLayout.setWidget(10, QtGui.QFormLayout.LabelRole, self.gotoXYZButton)
        self.gotoSqButton = QtGui.QPushButton(self.formLayoutWidget)
        self.gotoSqButton.setObjectName("gotoSqButton")
        self.formLayout.setWidget(11, QtGui.QFormLayout.LabelRole, self.gotoSqButton)
        self.gripperOpenButton = QtGui.QPushButton(self.formLayoutWidget)
        self.gripperOpenButton.setObjectName("gripperOpenButton")
        self.formLayout.setWidget(12, QtGui.QFormLayout.LabelRole, self.gripperOpenButton)
        self.gripperCloseButton = QtGui.QPushButton(self.formLayoutWidget)
        self.gripperCloseButton.setObjectName("gripperCloseButton")
        self.formLayout.setWidget(13, QtGui.QFormLayout.LabelRole, self.gripperCloseButton)
        self.imageGraphics = QtGui.QGraphicsView(self.centralWidget)
        self.imageGraphics.setGeometry(QtCore.QRect(280, 10, 400, 400))
        self.imageGraphics.setObjectName("imageGraphics")
        self.yLine = QtGui.QLineEdit(self.centralWidget)
        self.yLine.setGeometry(QtCore.QRect(150, 90, 113, 22))
        self.yLine.setObjectName("yLine")
        self.zLine = QtGui.QLineEdit(self.centralWidget)
        self.zLine.setGeometry(QtCore.QRect(150, 120, 113, 22))
        self.zLine.setObjectName("zLine")
        self.xLine = QtGui.QLineEdit(self.centralWidget)
        self.xLine.setGeometry(QtCore.QRect(150, 60, 113, 22))
        self.xLine.setObjectName("xLine")
        self.label = QtGui.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(130, 63, 16, 16))
        self.label.setObjectName("label")
        self.label_2 = QtGui.QLabel(self.centralWidget)
        self.label_2.setGeometry(QtCore.QRect(130, 94, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtGui.QLabel(self.centralWidget)
        self.label_3.setGeometry(QtCore.QRect(130, 123, 16, 16))
        self.label_3.setObjectName("label_3")
        self.sqLine = QtGui.QLineEdit(self.centralWidget)
        self.sqLine.setGeometry(QtCore.QRect(150, 20, 113, 22))
        self.sqLine.setObjectName("sqLine")
        self.label_4 = QtGui.QLabel(self.centralWidget)
        self.label_4.setGeometry(QtCore.QRect(110, 20, 41, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtGui.QLabel(self.centralWidget)
        self.label_5.setGeometry(QtCore.QRect(105, 153, 41, 20))
        self.label_5.setObjectName("label_5")
        self.fLine = QtGui.QLineEdit(self.centralWidget)
        self.fLine.setGeometry(QtCore.QRect(150, 150, 113, 22))
        self.fLine.setObjectName("fLine")
        self.tLine = QtGui.QLineEdit(self.centralWidget)
        self.tLine.setGeometry(QtCore.QRect(150, 180, 113, 22))
        self.tLine.setObjectName("tLine")
        self.label_6 = QtGui.QLabel(self.centralWidget)
        self.label_6.setGeometry(QtCore.QRect(110, 180, 41, 20))
        self.label_6.setObjectName("label_6")
        self.allInfo = QtGui.QLabel(self.centralWidget)
        self.allInfo.setGeometry(QtCore.QRect(120, 220, 141, 181))
        self.allInfo.setObjectName("allInfo")
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 697, 22))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName("mainToolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.stopButton.setText(QtGui.QApplication.translate("MainWindow", "Stop", None, QtGui.QApplication.UnicodeUTF8))
        self.connectButton.setText(QtGui.QApplication.translate("MainWindow", "Connect", None, QtGui.QApplication.UnicodeUTF8))
        self.resetButton.setText(QtGui.QApplication.translate("MainWindow", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.enableMotorsButton.setText(QtGui.QApplication.translate("MainWindow", "Motor En", None, QtGui.QApplication.UnicodeUTF8))
        self.disableMotorsButton.setText(QtGui.QApplication.translate("MainWindow", "Motor Dis", None, QtGui.QApplication.UnicodeUTF8))
        self.startWhiteButton.setText(QtGui.QApplication.translate("MainWindow", "Play White", None, QtGui.QApplication.UnicodeUTF8))
        self.initWhiteButton.setText(QtGui.QApplication.translate("MainWindow", "InitWhite", None, QtGui.QApplication.UnicodeUTF8))
        self.initBlackButton.setText(QtGui.QApplication.translate("MainWindow", "InitBlack", None, QtGui.QApplication.UnicodeUTF8))
        self.startBlackButton.setText(QtGui.QApplication.translate("MainWindow", "Play Black", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoXYZButton.setText(QtGui.QApplication.translate("MainWindow", "Goto XYZ", None, QtGui.QApplication.UnicodeUTF8))
        self.gotoSqButton.setText(QtGui.QApplication.translate("MainWindow", "Goto Sq", None, QtGui.QApplication.UnicodeUTF8))
        self.gripperOpenButton.setText(QtGui.QApplication.translate("MainWindow", "GOpen", None, QtGui.QApplication.UnicodeUTF8))
        self.gripperCloseButton.setText(QtGui.QApplication.translate("MainWindow", "GClose", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "X:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Y:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Field:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Theta:Z:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Time:", None, QtGui.QApplication.UnicodeUTF8))
        self.allInfo.setText(QtGui.QApplication.translate("MainWindow", "All Info", None, QtGui.QApplication.UnicodeUTF8))

